title: Алексей Лобзов о менеджменте и системном анализе
email: aleks.lobzov@gmail.com
description: Это мой блог, где я делюсь идеями и опытом, полученными в процессе моей профессиональной деятельности
baseurl: "/blog"
url: "https://alobzov.github.io"
github_username: alobzov
markdown: kramdown
author:
  name: "Алексей Лобзов"
  email: aleks.lobzov@gmail.com
encoding: utf-8
timezone: Europe/Moscow
paginate: 5
permalink: :year-:month-:day-:title.html
exclude:
  - README.md