name: markdown-link-check

on:
  push:
   branches:
   - main

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: './mlc_config.json'
        folder-path: '_posts'
        file-path: './README.md'